In [1]:
import torch
import numpy as np

In [2]:
x1 = torch.Tensor(5,3) # Construct a 5x3 matrix, uninitialized
print("x1:"); print(x1)
x2 = torch.rand(5,3) # Construct a randomly initialized matrix
print("x2:"); print(x2)
x3_ = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
x3 = torch.Tensor(x3_) # Construct matrix initialized by ndarray
print("x3:"); print(x3)
print(x3.size())

x1:
tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00],
        [-4.6566e-10,  5.6052e-45,  1.4714e-43],
        [ 1.5975e-43,  1.4153e-43,  1.3873e-43],
        [ 1.6255e-43,  1.5554e-43,  1.5975e-43],
        [ 1.6956e-43,  0.0000e+00,  0.0000e+00]])
x2:
tensor([[0.9248, 0.5633, 0.1780],
        [0.2122, 0.9026, 0.9705],
        [0.0096, 0.9726, 0.3816],
        [0.1054, 0.9072, 0.7188],
        [0.9670, 0.6383, 0.1880]])
x3:
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])
torch.Size([5, 3])


In [3]:
# Addition: syntax 1
y1 = torch.add(x2,x3)
print("y1:"); print(y1)

# Addition: syntax 2
y2 = x2 + x3
print("y2:"); print(y2)

# Addition: syntax 3
y3 = torch.Tensor(5,3)
torch.add(x2,x3,out=y3)
print("y3:"); print(y3)

# Addition: in place
y4 = x2.clone()
y4.add_(x3)
print("y4:"); print(y4)

y1:
tensor([[ 1.9248,  2.5633,  3.1780],
        [ 4.2122,  5.9026,  6.9705],
        [ 7.0096,  8.9726,  9.3816],
        [10.1054, 11.9072, 12.7188],
        [13.9670, 14.6383, 15.1880]])
y2:
tensor([[ 1.9248,  2.5633,  3.1780],
        [ 4.2122,  5.9026,  6.9705],
        [ 7.0096,  8.9726,  9.3816],
        [10.1054, 11.9072, 12.7188],
        [13.9670, 14.6383, 15.1880]])
y3:
tensor([[ 1.9248,  2.5633,  3.1780],
        [ 4.2122,  5.9026,  6.9705],
        [ 7.0096,  8.9726,  9.3816],
        [10.1054, 11.9072, 12.7188],
        [13.9670, 14.6383, 15.1880]])
y4:
tensor([[ 1.9248,  2.5633,  3.1780],
        [ 4.2122,  5.9026,  6.9705],
        [ 7.0096,  8.9726,  9.3816],
        [10.1054, 11.9072, 12.7188],
        [13.9670, 14.6383, 15.1880]])


In [5]:
# standard numpy-like indexing is supported
y5 = x3[0,:]
print("y5:"); print(y5)

y5:
tensor([1., 2., 3.])


In [6]:
# expand/squeeze dimensions
x3_hat = x3.clone()
x3_hat = torch.unsqueeze(x3_hat, 0) # [5,3] ----> [1,5,3]
print(x3_hat.size())
x3_hat = torch.squeeze(x3_hat) # [1,5,3] ----> [5,3]
print(x3_hat.size())

torch.Size([1, 5, 3])
torch.Size([5, 3])


In [7]:
# Numpy Bridge

# from Tensor to ndarray
a = torch.ones(3)
print("a:"); print(a)
b = a.numpy()
print("b:"); print(b)
a.add_(1)
print("b_new:"); print(b) # the value of ndarray changes according to torch Tensor

# from ndarray to Tensor
c = torch.from_numpy(b)
print("c:"); print(c)
a.add_(1)
print("c_new:"); print(c) # the values change in a chain: a->b->c

a:
tensor([1., 1., 1.])
b:
[1. 1. 1.]
b_new:
[2. 2. 2.]
c:
tensor([2., 2., 2.])
c_new:
tensor([3., 3., 3.])


In [10]:
# x2 = x2.cuda()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x2 = x2.to(device)
x3 = x3.to(device)
y = x2 + x3